$hyprDir = $HOME/.config/hypr
$wall = $HOME/.config/hyprlock/wallpapers/6.png

background {
    monitor =
    path = $wall
}

general {
    no_fade_in = false
    disable_loading_bar = false
    grace = 1
}

label {
    monitor =
    text = Welcome Sid!
    color = rgb(158, 206, 106) # Tokyo Night Orange (High Contrast)
    font_size = 55
    font_family = JetBrainsMono Nerd Font
    position = 0, 340
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M %p")</span>"
    color = rgb(122, 162, 247) # Tokyo Night Blue
    font_size = 40
    font_family = JetBrainsMono Nerd Font
    position = 0, 240
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %B %d')"
    color = rgba(192, 202, 245, 0.75) # Tokyo Night Text
    font_size = 20
    text_align = center
    font_family = JetBrainsMono Nerd Font
    position = 0, 175
    halign = center
    valign = center
}

label {
    monitor =
    text = 
    color = rgba(125, 207, 255, 0.9) # Tokyo Night Cyan
    font_size = 100
    font_family = JetBrainsMono Nerd Font
    position = 0, 25
    halign = center
    valign = center
}

shape {
    monitor =
    size = 320, 55
    color = rgba(88, 91, 112, 0.4)
    rounding = -1
    border_size = 0
    border_color = rgb(255, 255, 255)
    rotate = 0
    xray = false
    position = 0, -70
    halign = center
    valign = center
}

label {
    monitor =
    text =   $USER
    color = rgb(192, 202, 245) # Tokyo Night Text
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -70
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(88, 91, 112, 0.4)
    font_color = rgb(192, 202, 245) # Tokyo Night Text
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i><span foreground="##c0caf5">Enter Credentials</span></i>
    hide_input = false
    position = 0, -150
    halign = center
    valign = center
}
